apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api-green
  labels:
    service: todos-api
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      service: todos-api
      version: green
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: todos-api
        version: green
    spec:
      containers:
      - name: todos-api
        image: __IMAGE__
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: JWT_SECRET
          value: myfancysecret
        - name: TODO_API_PORT
          value: "8082"
        - name: REDIS_HOST
          value: redis-queue
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: log_channel
        - name: ZIPKIN_URL
          value: http://zipkin:9411/api/v2/spans
