apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
  labels:
    app: microservice-app-example
    service: todos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: todos-api
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: todos-api
    spec:
      containers:
      - name: todos-api
        image: 905418330989.dkr.ecr.us-east-1.amazonaws.com/todos-api:QA-todos-api-1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: JWT_SECRET
          value: myfancysecret
        - name: TODO_API_PORT
          value: "8082"
        - name: REDIS_HOST
          value: redis-queue
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: log_channel
        - name: ZIPKIN_URL
          value: http://zipkin:9411/api/v2/spans