apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor-green
  labels:
    service: log-message-processor
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      service: log-message-processor
      version: green
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: log-message-processor
        version: green
    spec:
      containers:
      - name: log-message-processor
        image: __IMAGE__
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: redis-queue
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: log_channel
        - name: ZIPKIN_URL
          value: http://zipkin:9411/api/v1/spans