apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
  labels:
    app: microservice-app-example
    service: log-message-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      service: log-message-processor
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: log-message-processor
    spec:
      containers:
      - name: log-message-processor
        image: 905418330989.dkr.ecr.us-east-1.amazonaws.com/log-message-processor:QA-log-message-processor-1.0
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: redis-queue
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: log_channel
        - name: ZIPKIN_URL
          value: http://zipkin:9411/api/v1/spans
