# todos-api service
apiVersion: v1
kind: Service
metadata:
  name: todos-api
  labels:
    app: microservice-app-example
    service: todos-api
spec:
  selector:
    service: todos-api
  ports:
  - port: 8082
    targetPort: 8082