apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-green
  labels:
    service: users-api
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      service: users-api
      version: green
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: users-api
        version: green
    spec:
      containers:
      - name: users-api
        image: __IMAGE__
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: JWT_SECRET
          value: myfancysecret
        - name: SERVER_PORT
          value: "8083"
        - name: SPRING_ZIPKIN_BASE_URL
          value: http://zipkin:9411