apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: microservice-app-example
    service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: frontend
    spec:
      containers:
      - name: frontend
        image: 905418330989.dkr.ecr.us-east-1.amazonaws.com/frontend:QA-frontend-1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_API_ADDRESS
          value: http://auth-api:8081
        - name: PORT
          value: "8080"
        - name: TODOS_API_ADDRESS
          value: http://todos-api:8082
        - name: ZIPKIN_URL
          value: http://zipkin:9411/api/v2/spans