apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: microservice-app-example
    service: frontend
spec:
  type: LoadBalancer
  selector:
    service: frontend
  ports:
  - port: 80
    targetPort: 8080