name: CD → Deploy via Dispatch

on:
  repository_dispatch:
    types: [ deploy ]

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: '035863456454'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name   ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy to Kubernetes
        env:
          SERVICE: ${{ github.event.client_payload.service }}
          IMAGE:   ${{ github.event.client_payload.image_uri }}
        run: |
          echo "Updating $SERVICE → $IMAGE"

          kubectl set image deployment/$SERVICE \
            $SERVICE=$IMAGE \
            --record

          kubectl rollout status deployment/$SERVICE